export type GridConfig = {
	Duration: number?,
	Color: Color3?,
	EasingStyle: Enum.EasingStyle?,
}

export type SlideConfig = {
	Duration: number?,
	Color: Color3?,
	Direction: string?,
	EasingStyle: Enum.EasingStyle?,
	ReverseOut: boolean?,
}

export type FadeConfig = {
	Duration: number?,
	Color: Color3?,
	EasingStyle: Enum.EasingStyle?,
}

export type IrisConfig = {
	Duration: number?,
	Color: Color3?,
	EasingStyle: Enum.EasingStyle?,
}

export type BlindsConfig = {
	Duration: number?,
	Color: Color3?,
	EasingStyle: Enum.EasingStyle?
}

export type SwipeConfig = {
	Duration: number?,
	Color: Color3?,
	EasingStyle: Enum.EasingStyle?
}

return {}
